#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

# Load modules
module load eb
module load Miniconda2

source deactivate

# Activate QIIME1 virtual environment
echo "loading virtualenv"
source activate qiime1

# Set temporary directory
export TMPDIR=~/qiime_tmp


# Compare categories
compare_categories.py \
--method adonis \
-i ~/2018/core_diversity_analyses/bdiv_even600/unweighted_unifrac_dm.txt \
-m ~/2018/map.tsv \
-c SampleDepth \
-o ~/2018/adonis_out \
-n 999


# Deactivate QIIME1 virtual environment
echo "Deactivating qiime1 virtual environment"
source deactivate
