#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

# Load modules
module load eb
module load Miniconda2

source deactivate

# Activate QIIME1 virtual environment
echo "loading virtualenv"
source activate qiime1

# Set temporary directory
export TMPDIR=~/qiime_tmp


#compare_categories
compare_categories.py \
--method adonis \
-i ~/2018_02_smb/ \
-o ~/2018_02_smb/compare_categories/P \
-c SamplePhosphorus \
-m ~/2018_02_smb/map.tsv \
-n 999


# Deactivate QIIME1 virtual environment
echo "Deactivating qiime1 virtual environment"
source deactivate 
