#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#SBATCH --reservation=cbmucl

# Load modules
module load eb
module load Miniconda2

source deactivate

# Activate QIIME1 virtual environment
echo "loading virtualenv"
source activate qiime1

# Set temporary directory
export TMPDIR=~/qiime_tmp


# Compute core microbiome
compute_core_microbiome.py \
-i ~/2018/de_novo_otus/otu_table.biom \
-o ~/2018/core_microbiome


# Deactivate QIIME1 virtual environment
echo "Deactivating qiime1 virtual environment"
source deactivate
