#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

# Load modules to run python
module load eb
module load Miniconda2

source deactivate

# Activate QIIME1 virtual environment
echo "loading qiime1 virtual environment"
source activate qiime1

# Setting temporary directory
export TMPDIR=~/qiime_tmp


# Demultiplex and quality filter
time split_libraries_fastq.py \
-m ~/2018_02_smb/map.tsv \
-i ~/2018_02_smb/read1.fastq.gz \
-b ~/2018_02_smb/index.fastq.gz \
-o ~/2018_02_smb/split_data/ \
-q 19 \
--barcode_type 12

# Deactivate QIIME1 virtual environment
echo "Deactivating qiime1 virtual environment"
source deactivate
