#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#SBATCH --reservation=cbmucl

# Load modules to run python
module load eb
module load Miniconda2

source deactivate

# Activate QIIME1 virtual environment
echo "loading qiime1 virtual environment"
source activate qiime1

# Setting temporary directory
export TMPDIR=~/qiime_tmp

# Demultiplex and quality filter
time split_libraries_fastq.py \
-m ~/2018/map.tsv \
-i ~/2018/read1.fastq.gz \
-b ~/2018/index.fastq.gz \
-o ~/2018/split_data/ \
-q 19 \
--barcode_type 12
